### ISSUE TITLE
Go code comments should follow godoc standard

### ISSUE THREAD

**Issue by aaronarduino** [Ennovar/gPanel#10]
### Severity level (1-10):

8

### Files/Directories Involved:

all Go files

### Description:

Go code comments should probably follow this guide: https://blog.golang.org/godoc-documenting-go-code

### Personal Comments:

This helps encourage contributions from the Go community because the comments would be what they are used to. Although, I think for the sake of ease of early development it would be good to keep the known problems section of the comment. Seems like a really useful section. The part of the comments that tell you about the input and output of the function isn't very helpful because it doesn't tell you anything new that the code doesn't already tell you.

For reference here is a large comment in the standard library: https://github.com/golang/go/blob/master/src/bufio/bufio.go#L350

Just some thoughts from someone who is excited about this project 😃

**Comment by jcbwlkr** [comment]
I agree with Aaron. Drop the formatted comments with `@param` and `@return` etc and just describe what the thing does and any special behaviors worth noting.

On the known problem thing you might consider the one special formatting that godoc supports which is `BUG(who)` like 

```
// BUG(george) This depends on an external service
```

which would then be show on the godoc page. This example

```
// BUG(r): The rule Title uses for word boundaries does not handle Unicode punctuation properly.
```
Shows up as https://golang.org/pkg/bytes/#pkg-note-BUG

**Comment by george-e-shaw-iv** [comment]
So how does this look for the contributing.md file?

## Stylistic & Conventions Guidelines

We follow all naming and style conventions that are officially put out by the developers of Go themselves. All of these rules and conventions can be found in their [Effective Go](https://golang.org/doc/effective_go.html) tutorial as well as [this Godoc](https://blog.golang.org/godoc-documenting-go-code) on documenting Go Code.

As this project is open source we do encourage commenting wherever may be necessary and require comments for all function declarations. The reason this is important is because it will increase productivity to whoever wants to come along and either add to or improve your code later on.

Go has [testing baked in the language](https://golang.org/pkg/testing/) and we would like there to be a test for nearly, if not all, functions that are in our program. If you don't write tests for your functions that you contribute, please note in the pull request that you did not.

### Examples of Well-documented Code

#### Function Blocks

```go
// This function returns the sum of two positive integers.
// When the two integers are not positive, it returns the zero-value of an integer and an error.
// BUG(george-e-shaw-iv) This function cannot handle negative integers
func addTwoPositiveIntegers(one int, two int) (int, error) {
  var answer int

  if one < 0 || two < 0 {
    return answer, errors.New("One or both of the input integers are negative")
  } else {
    answer = one + two
    return answer, nil
  }
}
```

#### Types, Variables, and Constants

```go
// A descriptive, custom data type for storing integers to be used in various time operations.
type Seconds int

// Variables don't always need comments, their name should give a good enough hint to what it does.
var cake string = "lie"

// These constants are used in various math and physics operations
const(
  PI  float32 = 3.14
  TAO float32 = 6.28
)
```

#### Packages

Package names should always match their parent folder.

```go
// This package contains various functions used to communicate between networks and
// draw data from the client network.
package networking
```

**Comment by jcbwlkr** [comment]
That looks pretty good. The only thing I would change is that comments need to start with the name of the thing they're describing

```go
// addTwoPositiveIntegers returns the sum of two positive integers.
// When the two integers are not positive, it returns the zero-value of an integer and an error.
// BUG(george-e-shaw-iv) This function cannot handle negative integers
func addTwoPositiveIntegers(one int, two int) (int, error) {
  var answer int

  if one < 0 || two < 0 {
    return answer, errors.New("One or both of the input integers are negative")
  } else {
    answer = one + two
    return answer, nil
  }
}
```

There's a slight variation for package comments

```go
// Package networking contains various functions used to communicate between networks and
// draw data from the client network.
package networking
```

The `golint` tool will complain about these things and guide you in that direction. For example run `golint ./...` from the root of the project to see that and a few other things you could improve.

**Comment by george-e-shaw-iv** [comment]
Sweet, let me know what you think of this now https://github.com/Ennovar/gPanel/blob/master/CONTRIBUTING.md

I forgot to reference the issue in my pull request because my mind has been kind of squirrely today haha.

Eventually when all of this pre-project stuff is out of the way, which in my opinion it nearly is, I'm gonna stop auto-merging things.
